/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.flolep;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ElectronServerTest {
}
